repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: Static Type Check
        entry: mypy --namespace-packages -p pytidb -p tests
        language: python
        types: [python]
        pass_filenames: false
        require_serial: true
