name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up TiDB
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker/tidb/docker-compose.yaml
          services: |
            tidb
            tiflash
      - name: Create directories for Docker volumes
        run: |
          mkdir -p ./docker/tidb/volumes/data/pd
          mkdir -p ./docker/tidb/volumes/data/tikv
          mkdir -p ./docker/tidb/volumes/logs
          # Set permissions to allow read/write by all users
          chmod -R a+rw ./docker/tidb/volumes/data
          chmod -R a+rw ./docker/tidb/volumes/logs
      - name: Wait tidb server started
        run: sleep 10
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - name: Install dependencies
        run: make install_dev
      - name: Run Lint
        run: make lint
      - name: Run Format
        run: make format
      - name: Run Test
        run: make test

