name: Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up TiDB
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker/tidb/docker-compose.yaml
          services: |
            tidb
            tiflash
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run Lint
        run: uv tool run ruff check
      - name: Run Format
        run: uv tool run ruff format
      - name: Run Test
        run: uv run pytest tests

