name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up TiDB
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker/tidb/docker-compose.yaml
          services: |
            tidb
            tiflash
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: make install_dev
      - name: Run Lint
        run: make lint
      - name: Run Format
        run: make format
      - name: Run Test
        run: make test

