name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up TiDB
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          source /home/runner/.profile
          nohup tiup playground v8.5.1 --without-monitor > tiup.log 2>&1 &
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - name: Install dependencies
        run: make install_dev
      - name: Run Lint
        run: make lint
      - name: Run Format
        run: make format
      - name: Run Test
        run: make test

