name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Docker images
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('docker/tidb/.keep', 'docker/tidb/docker-compose.yaml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Set up TiDB
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: docker/tidb/docker-compose.yaml
          services: |
            tidb
            tiflash
      - name: Wait tidb server started
        run: sleep 10
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: True
      - name: Install dependencies
        run: make install_dev
      - name: Run Lint
        run: make lint
      - name: Run Format
        run: make format
      - name: Run Test
        run: make test

